# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  install_aws_cli:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            pip3 install awscli

  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          # You can get this ID in the section where you registered the SSH Key
          fingerprints: ["2a:2f:a6:8a:e8:3e:bc:76:bc:53:ad:f8:82:a7:83:b4"]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Ansible Version
          command: |
            ansible --version
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main.yml
  
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test
          command: |
            URL="https://blog.udacity.com/"
            # Test if website exists
            if curl -s --head ${URL} 
            then
              return 0
            else
              return 1
            fi

workflows:
  my-workflow:
    jobs:
      - install_aws_cli
      #- configure_infrastructure:
      #    requires:
      #      - install_aws_cli
      - smoke_test