# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  install_aws_cli:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            pip3 install awscli

  configure_infrastructure: 
    docker:
      - image: ubuntu-2004:202010-01 # recommended linux image
    steps:
      - checkout
      - add_ssh_keys:
        # You can get this ID in the section where you registered the SSH Key
          fingerprints: ["1f:47:83:cc:b7:52:02:aa:2e:36:62:95:b8:e3:17:15"]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Ansible Version
          command: |
            ansible --version
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook main.yml -i inventory
workflows:
  my-workflow:
    jobs:
      - install_aws_cli
      - configure_infrastructure